### ISSUE TITLE
Template Preview fails

### ISSUE THREAD

**Issue by SeriousM** [wildbit/postmark-cli#21] opened 2019-12-19 10:44 UTC
Hi!

When I open `templates preview <path>` I get an error when I open the server:

```json
{
  "errno":-4058,
  "code":"ENOENT",
  "syscall":"open",
  "path":"C:\\dev\\MailTemplates\\preview\\index.ejs"
}
```

The path `C:\dev\MailTemplates\preview` doesn't even exist nor do I have an *.ejs file somewhere.

Is there anything I can do about it?

**Comment by derekrushforth** [comment] 2019-12-19 15:28
Hey @SeriousM! Sorry about the issues. Can you run `postmark --version` and tell me which version you're using?

**Comment by SeriousM** [comment] 2019-12-21 16:52
It was fresh installed from npm, but I'm not at my work place to look it
up.

**Comment by SeriousM** [comment] 2020-01-07 14:32
Alright, holidays over, here the required information.

```
    "postmark": "2.3.4",
    "postmark-cli": "1.3.6",
```

**Comment by viperfx** [comment] 2020-03-03 18:41
I get the same error 

```
{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/viperfx/.config/yarn/global/preview/index.ejs"}
```

Using latest version 1.4.6

**Comment by mattjennings** [comment] 2020-03-31 18:02
I'm also getting the same error. A workaround for this is use the following URLs and replacing `my-alias` with whichever template alias you want to preview

html preview: `http://localhost:3005/html/my-alias`

text preview: `http://localhost:3005/text/my-alias`

**Comment by derekrushforth** [comment] 2020-03-31 18:12
I'll get to the bottom of this issue. Sorry about the trouble, folks.

@mattjennings What OS are you using? And are you installing this via npm or yarn?

**Comment by mattjennings** [comment] 2020-03-31 18:17
macOS 10.15.3 and we're using yarn. It's installed in a monorepo as a project dependency, as well, and the path in my error points to the root directory of my monorepo:

```
"path":"/Users/mattjennings/dev/ttq/monorepo/preview/index.ejs"
```

`/Users/mattjennings/dev/ttq/monorepo/node_modules/postmark-cli` is where the package is installed.

I gave a quick look into the repo and it looks like this is the cause

https://github.com/wildbit/postmark-cli/blob/967140b3c27dc87851d9d9847578f74ca731d4cc/src/commands/templates/preview.ts#L15

**Comment by derekrushforth** [comment] 2020-03-31 18:19
@mattjennings Thanks for the info. Yeah, that's definitely the issue. I just need to figure out why it's not working with yarn. npm seems to be fine though.

**Comment by viperfx** [comment] 2020-04-01 16:31
@derekrushforth so the work around right now is to use npm install and run with npm? 

can you share your npm and node version.

**Comment by derekrushforth** [comment] 2020-04-01 19:55
Hey folks, can you install the latest version(1.4.7) of the CLI tool? I just pushed up a fix.

I've tested this using npm v6.13.4 and yarn v1.22.4.

**Comment by mattjennings** [comment] 2020-04-01 20:45
working as expected now! thanks for the fix.

**Comment by derekrushforth** [comment] 2020-04-06 14:31
Closing this issue out. Feel free to open it back up if anyone is still having issues.

**Closed by derekrushforth** 2020-04-06 14:31 UTC
Labels: bug
